export const ActionTypes = {
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_PRODUCT:"REMOVE_PRODUCT",
    GET_TOTAL:"GET_TOTAL",
    DECREMENT:"DECREMENT",
    SET_PRODUCTS  : "SET_PRODUCTS",
    GET_ALL_PRODUCT :"GET_ALL_PRODUCT",
    INCREASE_QTY : "INCREASE_QTY"

}